version: '3.7'
services:
  mongo1:
    image: mongo:5.0
    container_name: mongo1
    command: --bind_ip_all --replSet mongo-replica
    ports:
      - "27017:27017"
    networks:
      - cloudmind-network
  mongo2:
    image: mongo:5.0
    container_name: mongo2
    command: --bind_ip_all --replSet mongo-replica
    ports:
      - "27016:27017"
    networks:
      - cloudmind-network
  mongo3:
    image: mongo:5.0
    container_name: mongo3
    command: --bind_ip_all --replSet mongo-replica
    ports:
      - "27015:27017"
    networks:
      - cloudmind-network
  monstache:
    image: rwynn/monstache:latest
    restart: always
    container_name: monstache
    volumes:
      - ./etc/config.toml:/app/config.toml
    command: -f /app/config.toml
    networks:
      - cloudmind-network
  elasticsearch:
    image: elasticsearch:8.5.2
    container_name: elasticsearch
    user: elasticsearch:elasticsearch  # 指定非特权用户和组
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.type=single-node
      - xpack.security.enabled=false
      - TZ=Asia/Shanghai
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - cloudmind-network
  etcd:
    container_name: etcd       # 容器名 --name
    restart: always             # 总是重启
    image: bitnami/etcd:3.5.2
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://localhost:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - cloudmind-network
  # jaeger-collector 收集器
  jaeger-collector:
    image: jaegertracing/jaeger-collector
    container_name: jaeger-collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - LOG_LEVEL=debug
    ports:
      - "9411:9411"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
    networks:
      - cloudmind-network
  jaeger-query:
    image: jaegertracing/jaeger-query
    container_name: jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - LOG_LEVEL=debug
    ports:
      - "16686:16686"
      - "16687:16687"
    networks:
      - cloudmind-network
  jaeger-agent:
    image: jaegertracing/jaeger-agent
    container_name: jaeger-agent
    environment:
      - REPORTER_GRPC_HOST_PORT=jaeger-collector:14250
      - LOG_LEVEL=debug
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14271:14271"
    networks:
      - cloudmind-network
  redis:
    image: redis:7.0.0
    container_name: redis
    ports:
      - "36379:6379"
    environment:
      TZ: Asia/Shanghai
    command: "redis-server --requirepass admin  --appendonly yes"
    privileged: true
    restart: always
    sysctls:
      net.core.somaxconn: 1024
    networks:
      - cloudmind-network
  kibana:
    image: kibana:8.5.2
    container_name: kibana
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
      - TZ=Asia/Shanghai
    restart: always
    networks:
       -  cloudmind-network
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
networks:
  cloudmind-network:
    driver: bridge
