elasticsearch-urls = ["http://elasticsearch:9200"]
direct-read-namespaces = ["cloudmind_sts.auth"]
mongo-url = "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=mongo-replica"
direct-read-namespaces = ["cloudmind_sts.auth"]
namespace-regex = '^cloudmind_sts.*$'
gzip = true
stats = true
index-stats = true
elasticsearch-user = "elastic"
elasticsearch-password = ""
elasticsearch-max-conns = 4
elasticsearch-validate-pem-file = false
dropped-collections = true
dropped-databases = true
replay = false
resume = true
resume-write-unsafe = false
resume-name = "default"
resume-strategy = 1
index-files = true
file-highlighting = true
file-namespaces = ["users.fs.files"]
verbose = true
cluster-name = 'apollo'
exit-after-direct-reads = false